package dev.cheulsoon.jwikicore.composer;

import java.util.List;

import dev.cheulsoon.jwikicore.parser.ParsedComponent;

/**
 * Composes Parsed Component into HTML Text
 * @author qorcj
 *
 */
public class WikiComposer {
	
	public WikiComposer() {
		
	}
	
	/**
	 * Perform comose on the parsed Component and produces HTML text
	 * @param parsedComponent generated by WikiParser
	 * @return HTML text
	 */
	public String compose(List<ParsedComponent> parsedComponent) {
		return "";
	}

}
